/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register */
		post: operations["register"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login */
		post: operations["login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logout */
		post: operations["logout"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Me */
		get: operations["me"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update Me */
		patch: operations["update_me"];
		trace?: never;
	};
	"/education/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Educations */
		get: operations["get_educations"];
		put?: never;
		/** Create Education */
		post: operations["create_education"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/education/{education_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Education */
		get: operations["get_education"];
		/** Edit Education */
		put: operations["edit_education"];
		post?: never;
		/** Delete Education */
		delete: operations["delete_education"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/experience/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Experiences */
		get: operations["get_experiences"];
		put?: never;
		/** Create Experience */
		post: operations["create_experience"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/experience/{expirence_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Experience */
		get: operations["get_experience"];
		/** Edit Expirence */
		put: operations["edit_expirence"];
		post?: never;
		/** Delete Expirence */
		delete: operations["delete_expirence"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/google/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Start the Google sign in redirect flow
		 * @description Redirect the browser to Google's consent screen.
		 *
		 *     `next` is a path inside the frontend to land on afterwards, e.g.
		 *     `/auth/google/login?next=/dashboard`.
		 */
		get: operations["google_login"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/google/link/start": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Start linking Google to the signed in account
		 * @description Send the browser to Google, remembering who is linking.
		 *
		 *     The session is read from the cookie rather than through ``CurrentUser`` so
		 *     that a signed out visitor lands on the login page: this is a top level
		 *     navigation, and a JSON 401 would render as a raw page.
		 */
		get: operations["google_link_start"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/google/link": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Disconnect Google from the signed in account
		 * @description Remove the Google link, unless it is the only way in.
		 *
		 *     A passwordless user who unlinked their sole provider could never sign in
		 *     again, so that is refused rather than left to support.
		 */
		delete: operations["google_unlink"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/google/callback": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Google redirects here after the user consents
		 * @description Complete the handshake, set the session cookie, return to the frontend.
		 *
		 *     This is a browser navigation rather than an API call, so failures redirect
		 *     back to the frontend with an `auth_error` query param instead of returning
		 *     a JSON error the user would see as a raw page.
		 */
		get: operations["google_callback"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/google/token": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign in with an ID token from Google Identity Services
		 * @description Exchange the `credential` from Google's sign in button for a session.
		 */
		post: operations["google_token"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/personal-info/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get All Personal Info */
		get: operations["get_all_personal_info"];
		put?: never;
		/** Create Personal Info */
		post: operations["create_personal_info"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/personal-info/{personal_info_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Personal Info */
		get: operations["get_personal_info"];
		/** Edit Personal Info */
		put: operations["edit_personal_info"];
		post?: never;
		/** Delete Personal Info */
		delete: operations["delete_personal_info"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/project/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Projects */
		get: operations["get_projects"];
		put?: never;
		/** Create Project */
		post: operations["create_project"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/project/{project_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Project */
		get: operations["get_project"];
		/** Edit Project */
		put: operations["edit_project"];
		post?: never;
		/** Delete Project */
		delete: operations["delete_project"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/resumes/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Resumes */
		get: operations["get_resumes"];
		put?: never;
		/** Create Resume */
		post: operations["create_resume"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/resumes/{resume_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Resume */
		get: operations["get_resume"];
		/** Edit Resume */
		put: operations["edit_resume"];
		post?: never;
		/** Delete Resume */
		delete: operations["delete_resume"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/resumes/{resume_id}/sections": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Resume Sections */
		get: operations["get_resume_sections"];
		/**
		 * Replace Resume Sections
		 * @description Replace the whole membership list.
		 *
		 *     Position is taken from the index within each type's run, so the request
		 *     body states the intended order outright rather than patching it.
		 */
		put: operations["replace_resume_sections"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/resumes/{resume_id}/document": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Resume Document
		 * @description The whole resume, resolved and ordered, in the shape a renderer wants.
		 *
		 *     The PDF worker builds the same structure from the same rows, so this stays
		 *     a view onto shared logic rather than a second implementation of it.
		 */
		get: operations["get_resume_document"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/resumes/{resume_id}/pdf": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Compile Resume Pdf
		 * @description Typeset the resume and hand back the PDF.
		 *
		 *     The source is generated in the worker from this resume's own rows, so
		 *     nothing about the document crosses the wire on the way in and there is no
		 *     caller-supplied LaTeX to distrust.
		 *
		 *     The wait here is deliberate: the client asked for a file and gets one in
		 *     the same response. The queue is not hiding the work, it is bounding how
		 *     much of it runs at once — a compile is CPU-bound, and unbounded exports
		 *     would take the host down rather than merely queue. A local install has no
		 *     host to protect and no queue to reach, so it typesets in this process
		 *     instead; both paths raise the same failures, which is why only the call
		 *     differs and none of the handling below does.
		 */
		post: operations["compile_resume_pdf"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/skill/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Skills */
		get: operations["get_skills"];
		put?: never;
		/** Create Skill */
		post: operations["create_skill"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/skill/{skill_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Skill */
		get: operations["get_skill"];
		/** Edit Skill */
		put: operations["edit_skill"];
		post?: never;
		/** Delete Skill */
		delete: operations["delete_skill"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sync/changes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Pull Changes
		 * @description Everything that has happened to this account's records since ``since``.
		 *
		 *     Paged rather than complete, because a library that has been edited for
		 *     years is not something to assemble in memory on either end. Changes are not
		 *     collapsed to the latest state of each record: replaying an intermediate
		 *     version costs a write the client would have made anyway, and collapsing
		 *     within a page would mean deciding what "latest" means without having seen
		 *     the pages after it.
		 */
		get: operations["pull_changes"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sync/push": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Push Changes
		 * @description Offer changes made elsewhere, and be told what became of each.
		 *
		 *     Each change carries the version of its record that the client last agreed
		 *     with this server. If that is still the version here, nobody else has
		 *     touched it and the change is applied. If it is not, both sides changed the
		 *     same record and this says so rather than choosing — the response carries
		 *     what the server has, which is the other half of the question a person then
		 *     gets asked.
		 *
		 *     Applied one at a time rather than as a single transaction, because the
		 *     answer is per record: one conflicted resume should not send back a whole
		 *     library that would otherwise have gone through. A client re-offers what did
		 *     not land.
		 */
		post: operations["push_changes"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sync/status": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Sync Status
		 * @description Whether this library is connected to an account, and what is outstanding.
		 */
		get: operations["sync_status"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sync/connect": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Connect Account
		 * @description Sign this library in to an account.
		 *
		 *     Nothing is transferred here. Connecting only records who this library
		 *     belongs to; the first sync afterwards is what carries the work across, and
		 *     it is the same code as every sync after it rather than a special first one.
		 */
		post: operations["connect_account"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sync/disconnect": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Disconnect Account
		 * @description Forget the account. The library stays exactly as it is.
		 */
		post: operations["disconnect_account"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sync/run": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Run Sync
		 * @description Bring this library and the account level with each other.
		 */
		post: operations["run_sync"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/sync/conflicts/{record_id}/resolve": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Resolve
		 * @description Say which side of a disagreement was meant.
		 *
		 *     The choice is recorded here and carried out by the next sync, so answering
		 *     a pile of conflicts is not a pile of network calls that can half fail.
		 */
		post: operations["resolve"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * BulletPoint
		 * @description A line of resume text plus the runs of it that render bold.
		 *
		 *     Each range in ``bolded`` is a pair of **inclusive** character indices into
		 *     ``text``: ``(0, 6)`` over ``"Shipped it"`` bolds ``"Shipped"``. Ranges must
		 *     arrive sorted and disjoint, so a renderer can walk them in one pass and
		 *     cannot be handed overlaps that would nest one bold inside another.
		 */
		BulletPoint: {
			/** Text */
			text: string;
			/** Bolded */
			bolded: [number, number][];
		};
		/**
		 * Change
		 * @description One thing that happened to one record.
		 *
		 *     The snapshot is the record as it stood, not a pointer to it, which is what
		 *     lets a delete be transferred at all: by the time anyone asks, the row it
		 *     describes is gone.
		 */
		Change: {
			record_type: components["schemas"]["SectionType"];
			/**
			 * Record Id
			 * Format: uuid
			 */
			record_id: string;
			/** Version */
			version: number;
			operation: components["schemas"]["OperationType"];
			/** Snapshot */
			snapshot: {
				[key: string]: unknown;
			};
			/** Seq */
			seq: number;
		};
		/**
		 * ChangeFeed
		 * @description A page of history, oldest first.
		 */
		ChangeFeed: {
			/** Changes */
			changes: components["schemas"]["Change"][];
			/** Cursor */
			cursor: number;
			/** More */
			more: boolean;
		};
		/**
		 * ConflictRead
		 * @description A record both sides changed, and both answers to choose between.
		 */
		ConflictRead: {
			/**
			 * Record Id
			 * Format: uuid
			 */
			record_id: string;
			record_type: components["schemas"]["SectionType"];
			/** Local Version */
			local_version: number;
			/** Cloud Version */
			cloud_version: number;
			/** Local Snapshot */
			local_snapshot: {
				[key: string]: unknown;
			};
			/** Cloud Snapshot */
			cloud_snapshot: {
				[key: string]: unknown;
			};
		};
		/**
		 * ConnectRequest
		 * @description Sign this library in to an account.
		 */
		ConnectRequest: {
			/** Base Url */
			base_url: string;
			/** Email */
			email: string;
			/** Password */
			password: string;
		};
		/** EducationBlock */
		EducationBlock: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: "education";
			/** Items */
			items: components["schemas"]["EducationRead"][];
		};
		/** EducationCreate */
		EducationCreate: {
			/** Name */
			name: string;
			/** Subheading */
			subheading: string;
			/** Duration */
			duration: string;
			/** Location */
			location: string;
		};
		/** EducationRead */
		EducationRead: {
			/** Name */
			name: string;
			/** Subheading */
			subheading: string;
			/** Duration */
			duration: string;
			/** Location */
			location: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/** ErrorDetail */
		ErrorDetail: {
			/** Detail */
			detail: string;
		};
		/** ExperienceBlock */
		ExperienceBlock: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: "experience";
			/** Items */
			items: components["schemas"]["ExpirenceRead"][];
		};
		/** ExpirenceCreate */
		ExpirenceCreate: {
			/** Company */
			company: string;
			/** Position */
			position: string;
			/** Duration */
			duration: string;
			/** Location */
			location: string;
			/** Bullet Points */
			bullet_points: components["schemas"]["BulletPoint"][];
		};
		/** ExpirenceRead */
		ExpirenceRead: {
			/** Company */
			company: string;
			/** Position */
			position: string;
			/** Duration */
			duration: string;
			/** Location */
			location: string;
			/** Bullet Points */
			bullet_points: components["schemas"]["BulletPoint"][];
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/**
		 * GoogleCredential
		 * @description The ID token Google Identity Services hands the frontend.
		 */
		GoogleCredential: {
			/** Credential */
			credential: string;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/**
		 * Link
		 * @description A URL paired with the text a resume shows in its place.
		 *
		 *     `label` is optional: a caller that only has the URL can omit it, and the
		 *     renderer falls back to showing the URL itself.
		 */
		Link: {
			/** Url */
			url: string;
			/** Label */
			label?: string | null;
		};
		/**
		 * OperationType
		 * @description What a version snapshot records the section as having undergone.
		 * @enum {string}
		 */
		OperationType: "create" | "update" | "delete";
		/**
		 * PersonalInfoCreate
		 * @description The full representation, used to create a row and to replace one.
		 *
		 *     Every field is optional, so on a create an omitted field is stored as null
		 *     and on a replace it clears whatever was there.
		 */
		PersonalInfoCreate: {
			/** Email */
			email?: string | null;
			/** Phone Number */
			phone_number?: string | null;
			/** Address */
			address?: string | null;
			github?: components["schemas"]["Link"] | null;
			linkedin?: components["schemas"]["Link"] | null;
			portfolio?: components["schemas"]["Link"] | null;
		};
		/** PersonalInfoRead */
		PersonalInfoRead: {
			/** Email */
			email?: string | null;
			/** Phone Number */
			phone_number?: string | null;
			/** Address */
			address?: string | null;
			github?: components["schemas"]["Link"] | null;
			linkedin?: components["schemas"]["Link"] | null;
			portfolio?: components["schemas"]["Link"] | null;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/** ProjectBlock */
		ProjectBlock: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: "project";
			/** Items */
			items: components["schemas"]["ProjectRead"][];
		};
		/** ProjectCreate */
		ProjectCreate: {
			/** Name */
			name: string;
			/** Link */
			link?: string | null;
			/** Technologies */
			technologies: string[];
			/** Bullet Points */
			bullet_points: components["schemas"]["BulletPoint"][];
		};
		/** ProjectRead */
		ProjectRead: {
			/** Name */
			name: string;
			/** Link */
			link?: string | null;
			/** Technologies */
			technologies: string[];
			/** Bullet Points */
			bullet_points: components["schemas"]["BulletPoint"][];
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/**
		 * PushChange
		 * @description A change made elsewhere, offered to this database.
		 *
		 *     ``base_version`` is the version of this record the client last agreed with
		 *     the server. It is the whole of conflict detection: if the server has moved
		 *     past it, somebody else changed the same record in the meantime and nobody
		 *     but a person can say which of the two was meant.
		 *
		 *     ``None`` means "I believe you have never seen this record" — a record
		 *     created offline. It is checked rather than trusted, so claiming it for a
		 *     record the server does know about is a conflict like any other.
		 */
		PushChange: {
			record_type: components["schemas"]["SectionType"];
			/**
			 * Record Id
			 * Format: uuid
			 */
			record_id: string;
			/** Base Version */
			base_version?: number | null;
			operation: components["schemas"]["OperationType"];
			/** Snapshot */
			snapshot?: {
				[key: string]: unknown;
			};
		};
		/**
		 * PushOutcome
		 * @enum {string}
		 */
		PushOutcome: "applied" | "conflict" | "rejected";
		/** PushRequest */
		PushRequest: {
			/** Changes */
			changes: components["schemas"]["PushChange"][];
		};
		/** PushResponse */
		PushResponse: {
			/** Results */
			results: components["schemas"]["PushResult"][];
		};
		/**
		 * PushResult
		 * @description What became of one offered change.
		 */
		PushResult: {
			/**
			 * Record Id
			 * Format: uuid
			 */
			record_id: string;
			record_type: components["schemas"]["SectionType"];
			outcome: components["schemas"]["PushOutcome"];
			/** Version */
			version?: number | null;
			/** Seq */
			seq?: number | null;
			theirs?: components["schemas"]["Change"] | null;
			/** Reason */
			reason?: string | null;
		};
		/** ResolveRequest */
		ResolveRequest: {
			/**
			 * Choice
			 * @enum {string}
			 */
			choice: "mine" | "theirs";
		};
		/**
		 * ResumeCreate
		 * @description A new resume. Everything but the title has a usable default.
		 *
		 *     Sections may be attached here rather than in a second call, because the
		 *     editor builds a resume and its contents in one modal and there is no
		 *     reason to make it save twice.
		 */
		ResumeCreate: {
			/** Title */
			title: string;
			/**
			 * Template
			 * @default jakes
			 */
			template: string;
			/** Full Name */
			full_name?: string | null;
			/** Personal Info Id */
			personal_info_id?: string | null;
			/** Section Order */
			section_order?: components["schemas"]["ResumeSectionType"][];
			/**
			 * Sections
			 * @default []
			 */
			sections: components["schemas"]["ResumeSectionRef"][];
		};
		/**
		 * ResumeDocument
		 * @description Everything a renderer needs, resolved and in order, in one response.
		 *
		 *     Bullet points are hydrated and blocks arrive in ``section_order``, so a
		 *     client can walk the structure straight into a template without a second
		 *     request or any sorting of its own. Blocks with no items are dropped, since
		 *     an empty section would otherwise render as a bare heading.
		 */
		ResumeDocument: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Title */
			title: string;
			/** Template */
			template: string;
			/** Full Name */
			full_name: string;
			personal_info?: components["schemas"]["PersonalInfoRead"] | null;
			/** Sections */
			sections: (
				| components["schemas"]["EducationBlock"]
				| components["schemas"]["ExperienceBlock"]
				| components["schemas"]["ProjectBlock"]
				| components["schemas"]["SkillBlock"]
			)[];
		};
		/**
		 * ResumeEdit
		 * @description The full representation a replace has to send.
		 */
		ResumeEdit: {
			/** Title */
			title: string;
			/**
			 * Template
			 * @default jakes
			 */
			template: string;
			/** Full Name */
			full_name?: string | null;
			/** Personal Info Id */
			personal_info_id?: string | null;
			/** Section Order */
			section_order?: components["schemas"]["ResumeSectionType"][];
		};
		/** ResumeRead */
		ResumeRead: {
			/** Title */
			title: string;
			/**
			 * Template
			 * @default jakes
			 */
			template: string;
			/** Full Name */
			full_name?: string | null;
			/** Personal Info Id */
			personal_info_id?: string | null;
			/** Section Order */
			section_order?: components["schemas"]["ResumeSectionType"][];
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/**
		 * ResumeSectionRef
		 * @description A pointer to one of the caller's sections, by type and id.
		 */
		ResumeSectionRef: {
			section_type: components["schemas"]["ResumeSectionType"];
			/**
			 * Section Id
			 * Format: uuid
			 */
			section_id: string;
		};
		/**
		 * ResumeSectionType
		 * @description The section kinds a resume orders and renders as headed blocks.
		 *
		 *     Deliberately narrower than ``SectionType``: personal info is the header of
		 *     a resume rather than one of its sections, so it hangs off ``Resume``
		 *     directly and cannot be expressed here.
		 * @enum {string}
		 */
		ResumeSectionType: "education" | "experience" | "project" | "skill";
		/**
		 * ResumeSectionsReplace
		 * @description The whole membership list at once.
		 *
		 *     Position is the index within the run of entries sharing a type, so
		 *     reordering is a rewrite of the list rather than a separate operation —
		 *     the same trade the skill lists make.
		 */
		ResumeSectionsReplace: {
			/** Sections */
			sections: components["schemas"]["ResumeSectionRef"][];
		};
		/**
		 * RunReport
		 * @description What one sync did.
		 */
		RunReport: {
			/** Pulled */
			pulled: number;
			/** Pushed */
			pushed: number;
			/** Conflicts */
			conflicts: string[];
			/** Rejected */
			rejected: string[];
		};
		/**
		 * SectionType
		 * @description The kinds of record that carry version history.
		 *
		 *     Mostly section kinds, plus the resume itself — a resume is not a section of
		 *     anything, but it is a thing a person edits and therefore a thing that has
		 *     to be carried between a desktop and an account, in the same order as
		 *     everything else. One history is what lets a sync read a user's changes as a
		 *     single sequence rather than merging several.
		 *
		 *     The member values are the stored labels in both Postgres and JSON: the
		 *     column passes ``db.enum_values`` to ``values_callable`` so the type's
		 *     labels are these rather than the member names, and Pydantic serializes a
		 *     ``str`` enum by its value. Adding a member therefore changes the API
		 *     contract and the database type together.
		 * @enum {string}
		 */
		SectionType:
			| "education"
			| "experience"
			| "personal_info"
			| "project"
			| "skill"
			| "resume";
		/** SkillBlock */
		SkillBlock: {
			/**
			 * @description discriminator enum property added by openapi-typescript
			 * @enum {string}
			 */
			type: "skill";
			/** Items */
			items: components["schemas"]["SkillRead"][];
		};
		/** SkillCreate */
		SkillCreate: {
			/** Name */
			name: string;
			/** Items */
			items: string[];
			/** Position */
			position?: number | null;
		};
		/**
		 * SkillEdit
		 * @description The full representation a replace has to send.
		 *
		 *     Unlike `SkillCreate`, `position` is required: there is no list to append
		 *     after, only an existing one whose place the caller has to state.
		 */
		SkillEdit: {
			/** Name */
			name: string;
			/** Items */
			items: string[];
			/** Position */
			position: number;
		};
		/** SkillRead */
		SkillRead: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
			/** Items */
			items: string[];
			/** Position */
			position: number;
		};
		/**
		 * SyncStatus
		 * @description Everything the window needs to say where this library stands.
		 */
		SyncStatus: {
			/** Connected */
			connected: boolean;
			/** Account Email */
			account_email?: string | null;
			/**
			 * Cloud Cursor
			 * @default 0
			 */
			cloud_cursor: number;
			/**
			 * Local Cursor
			 * @default 0
			 */
			local_cursor: number;
			/** Conflicts */
			conflicts?: components["schemas"]["ConflictRead"][];
		};
		/** UserCreate */
		UserCreate: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Password */
			password: string;
		};
		/** UserLogin */
		UserLogin: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Password */
			password: string;
		};
		/** UserRead */
		UserRead: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Name */
			name: string | null;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Sign In Methods */
			sign_in_methods: string[];
		};
		/**
		 * UserUpdate
		 * @description The parts of a profile its owner may change.
		 */
		UserUpdate: {
			/** Name */
			name?: string | null;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	register: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserLogin"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	update_me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserUpdate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_educations: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_education: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["EducationCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_education: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				education_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_education: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				education_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["EducationCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_education: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				education_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_experiences: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_experience: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ExpirenceCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_experience: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				expirence_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_expirence: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				expirence_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ExpirenceCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_expirence: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				expirence_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	google_login: {
		parameters: {
			query?: {
				next?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			307: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	google_link_start: {
		parameters: {
			query?: {
				next?: string;
			};
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			307: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	google_unlink: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	google_callback: {
		parameters: {
			query?: {
				code?: string | null;
				state?: string | null;
				error?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: {
				oauth_state?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			307: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	google_token: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["GoogleCredential"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_all_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PersonalInfoCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				personal_info_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				personal_info_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PersonalInfoCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				personal_info_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_projects: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_project: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ProjectCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_project: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_project: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ProjectCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_project: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_resumes: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResumeRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_resume: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ResumeCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResumeRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_resume: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resume_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResumeRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_resume: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resume_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ResumeEdit"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResumeRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_resume: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resume_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResumeRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_resume_sections: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resume_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResumeSectionsReplace"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	replace_resume_sections: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resume_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ResumeSectionsReplace"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResumeSectionsReplace"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_resume_document: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resume_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResumeDocument"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	compile_resume_pdf: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				resume_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/pdf": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_skills: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_skill: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SkillCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_skill: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_skill: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SkillEdit"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_skill: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	pull_changes: {
		parameters: {
			query?: {
				since?: number;
				limit?: number;
			};
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ChangeFeed"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	push_changes: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PushRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PushResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	sync_status: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SyncStatus"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	connect_account: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ConnectRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SyncStatus"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	disconnect_account: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	run_sync: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RunReport"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	resolve: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				record_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ResolveRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SyncStatus"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
}
