/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Register */
		post: operations["register"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Login */
		post: operations["login"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logout */
		post: operations["logout"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Me */
		get: operations["me"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/education/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Educations */
		get: operations["get_educations"];
		put?: never;
		/** Create Education */
		post: operations["create_education"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/education/{education_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Education */
		get: operations["get_education"];
		/** Edit Education */
		put: operations["edit_education"];
		post?: never;
		/** Delete Education */
		delete: operations["delete_education"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/experience/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Experiences */
		get: operations["get_experiences"];
		put?: never;
		/** Create Experience */
		post: operations["create_experience"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/experience/{expirence_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Experience */
		get: operations["get_experience"];
		/** Edit Expirence */
		put: operations["edit_expirence"];
		post?: never;
		/** Delete Expirence */
		delete: operations["delete_expirence"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/google/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Start the Google sign in redirect flow
		 * @description Redirect the browser to Google's consent screen.
		 *
		 *     `next` is a path inside the frontend to land on afterwards, e.g.
		 *     `/auth/google/login?next=/dashboard`.
		 */
		get: operations["google_login"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/google/callback": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Google redirects here after the user consents
		 * @description Complete the handshake, set the session cookie, return to the frontend.
		 *
		 *     This is a browser navigation rather than an API call, so failures redirect
		 *     back to the frontend with an `auth_error` query param instead of returning
		 *     a JSON error the user would see as a raw page.
		 */
		get: operations["google_callback"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/google/token": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign in with an ID token from Google Identity Services
		 * @description Exchange the `credential` from Google's sign in button for a session.
		 */
		post: operations["google_token"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/personal-info/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get All Personal Info */
		get: operations["get_all_personal_info"];
		put?: never;
		/** Create Personal Info */
		post: operations["create_personal_info"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/personal-info/{personal_info_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Personal Info */
		get: operations["get_personal_info"];
		/** Edit Personal Info */
		put: operations["edit_personal_info"];
		post?: never;
		/** Delete Personal Info */
		delete: operations["delete_personal_info"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/project/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Projects */
		get: operations["get_projects"];
		put?: never;
		/** Create Project */
		post: operations["create_project"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/project/{project_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Project */
		get: operations["get_project"];
		/** Edit Project */
		put: operations["edit_project"];
		post?: never;
		/** Delete Project */
		delete: operations["delete_project"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/skill/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Skills */
		get: operations["get_skills"];
		put?: never;
		/** Create Skill */
		post: operations["create_skill"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/skill/{skill_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Skill */
		get: operations["get_skill"];
		/** Edit Skill */
		put: operations["edit_skill"];
		post?: never;
		/** Delete Skill */
		delete: operations["delete_skill"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** BulletPoint */
		BulletPoint: {
			/** Text */
			text: string;
			/** Bolded */
			bolded: [number, number][];
		};
		/** EducationCreate */
		EducationCreate: {
			/** Name */
			name: string;
			/** Subheading */
			subheading: string;
			/** Duration */
			duration: string;
			/** Location */
			location: string;
		};
		/** EducationRead */
		EducationRead: {
			/** Name */
			name: string;
			/** Subheading */
			subheading: string;
			/** Duration */
			duration: string;
			/** Location */
			location: string;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/** ErrorDetail */
		ErrorDetail: {
			/** Detail */
			detail: string;
		};
		/** ExpirenceCreate */
		ExpirenceCreate: {
			/** Company */
			company: string;
			/** Position */
			position: string;
			/** Duration */
			duration: string;
			/** Location */
			location: string;
			/** Bullet Points */
			bullet_points: components["schemas"]["BulletPoint"][];
		};
		/** ExpirenceRead */
		ExpirenceRead: {
			/** Company */
			company: string;
			/** Position */
			position: string;
			/** Duration */
			duration: string;
			/** Location */
			location: string;
			/** Bullet Points */
			bullet_points: components["schemas"]["BulletPoint"][];
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/**
		 * GoogleCredential
		 * @description The ID token Google Identity Services hands the frontend.
		 */
		GoogleCredential: {
			/** Credential */
			credential: string;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/**
		 * PersonalInfoCreate
		 * @description The full representation, used to create a row and to replace one.
		 *
		 *     Every field is optional, so on a create an omitted field is stored as null
		 *     and on a replace it clears whatever was there.
		 */
		PersonalInfoCreate: {
			/** Email */
			email?: string | null;
			/** Phone Number */
			phone_number?: string | null;
			/** Address */
			address?: string | null;
			/** Github */
			github?: string | null;
			/** Linkedin */
			linkedin?: string | null;
			/** Portfolio */
			portfolio?: string | null;
		};
		/** PersonalInfoRead */
		PersonalInfoRead: {
			/** Email */
			email?: string | null;
			/** Phone Number */
			phone_number?: string | null;
			/** Address */
			address?: string | null;
			/** Github */
			github?: string | null;
			/** Linkedin */
			linkedin?: string | null;
			/** Portfolio */
			portfolio?: string | null;
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/** ProjectCreate */
		ProjectCreate: {
			/** Name */
			name: string;
			/** Link */
			link?: string | null;
			/** Technologies */
			technologies: string[];
			/** Bullet Points */
			bullet_points: components["schemas"]["BulletPoint"][];
		};
		/** ProjectRead */
		ProjectRead: {
			/** Name */
			name: string;
			/** Link */
			link?: string | null;
			/** Technologies */
			technologies: string[];
			/** Bullet Points */
			bullet_points: components["schemas"]["BulletPoint"][];
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
		};
		/** SkillCreate */
		SkillCreate: {
			/** Name */
			name: string;
			/** Items */
			items: string[];
			/** Position */
			position?: number | null;
		};
		/**
		 * SkillEdit
		 * @description The full representation a replace has to send.
		 *
		 *     Unlike `SkillCreate`, `position` is required: there is no list to append
		 *     after, only an existing one whose place the caller has to state.
		 */
		SkillEdit: {
			/** Name */
			name: string;
			/** Items */
			items: string[];
			/** Position */
			position: number;
		};
		/** SkillRead */
		SkillRead: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/** Name */
			name: string;
			/** Items */
			items: string[];
			/** Position */
			position: number;
		};
		/** UserCreate */
		UserCreate: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Password */
			password: string;
		};
		/** UserLogin */
		UserLogin: {
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Password */
			password: string;
		};
		/** UserRead */
		UserRead: {
			/**
			 * Id
			 * Format: uuid
			 */
			id: string;
			/**
			 * Email
			 * Format: email
			 */
			email: string;
			/** Name */
			name: string | null;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	register: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	login: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UserLogin"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	logout: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	me: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_educations: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_education: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["EducationCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_education: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				education_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_education: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				education_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["EducationCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_education: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				education_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EducationRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_experiences: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_experience: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ExpirenceCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_experience: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				expirence_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_expirence: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				expirence_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ExpirenceCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_expirence: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				expirence_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ExpirenceRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	google_login: {
		parameters: {
			query?: {
				next?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			307: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	google_callback: {
		parameters: {
			query?: {
				code?: string | null;
				state?: string | null;
				error?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: {
				oauth_state?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			307: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	google_token: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["GoogleCredential"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["UserRead"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ErrorDetail"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_all_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PersonalInfoCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				personal_info_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				personal_info_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["PersonalInfoCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_personal_info: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				personal_info_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PersonalInfoRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_projects: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_project: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ProjectCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_project: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_project: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ProjectCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_project: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				project_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_skills: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_skill: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SkillCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_skill: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	edit_skill: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SkillEdit"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_skill: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_id: string;
			};
			cookie?: {
				access_token?: string | null;
			};
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillRead"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
}
