"""add users table

Revision ID: 1d5b17e3028f
Revises: f5f36408d06f
Create Date: 2026-08-08 21:26:06.063338

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1d5b17e3028f"
down_revision: str | Sequence[str] | None = "f5f36408d06f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
