"""added section version table for storing section histories

Revision ID: 4d97d14083fa
Revises: e303e53f5600
Create Date: 2026-08-15 17:01:30.281078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d97d14083fa'
down_revision: Union[str, Sequence[str], None] = 'e303e53f5600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.Enum('education', 'experience', 'personal_info', 'project', 'skill', name='section_version_type'), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('create', 'update', 'delete', name='section_version_operation'), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_type', 'section_id', 'version', name='uq_section_versions_section_version')
    )
    op.create_index(op.f('ix_section_versions_user_id'), 'section_versions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_section_versions_user_id'), table_name='section_versions')
    op.drop_table('section_versions')
    # ### end Alembic commands ###

    # dropping the table leaves its enum types behind, so a later re-upgrade
    # would fail on the CREATE TYPE that op.create_table emits for them
    sa.Enum(name='section_version_type').drop(op.get_bind())
    sa.Enum(name='section_version_operation').drop(op.get_bind())
