"""a local database remembers its account

Revision ID: 78d817c69cb8
Revises: e854a7c9b579
Create Date: 2026-09-03 12:37:17.395082

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from db import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "78d817c69cb8"
down_revision: str | Sequence[str] | None = "e854a7c9b579"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


RECORD_TYPE_VALUES = (
    "education",
    "experience",
    "personal_info",
    "project",
    "skill",
    "resume",
)


def record_type_column() -> sa.Column[str]:
    """The record kind, reusing the type the history already declares.

    Postgres would otherwise try to create ``section_version_type`` a second
    time and fail on a type that is already there; SQLite has no such type at
    all and stores the value as text either way.
    """
    if op.get_bind().dialect.name == "postgresql":
        enum: sa.types.TypeEngine[str] = postgresql.ENUM(
            *RECORD_TYPE_VALUES, name="section_version_type", create_type=False
        )
    else:
        enum = sa.Enum(*RECORD_TYPE_VALUES, name="section_version_type")

    return sa.Column("record_type", enum, nullable=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_agreements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        record_type_column(),
        sa.Column("local_version", sa.Integer(), nullable=False),
        sa.Column("cloud_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            UtcDateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            UtcDateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "record_id", name="uq_sync_agreements_record"),
    )
    op.create_index(
        op.f("ix_sync_agreements_record_id"),
        "sync_agreements",
        ["record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sync_agreements_user_id"), "sync_agreements", ["user_id"], unique=False
    )
    op.create_table(
        "sync_conflicts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        record_type_column(),
        sa.Column("local_version", sa.Integer(), nullable=False),
        sa.Column("cloud_version", sa.Integer(), nullable=False),
        sa.Column(
            "local_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "cloud_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            UtcDateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            UtcDateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "record_id", name="uq_sync_conflicts_record"),
    )
    op.create_index(
        op.f("ix_sync_conflicts_user_id"), "sync_conflicts", ["user_id"], unique=False
    )
    op.create_table(
        "sync_state",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_email", sa.String(length=255), nullable=False),
        sa.Column("cloud_base_url", sa.String(length=2048), nullable=False),
        sa.Column("access_token", sa.String(length=2048), nullable=True),
        sa.Column("cloud_cursor", sa.Integer(), nullable=False),
        sa.Column("local_cursor", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            UtcDateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            UtcDateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_state_user_id"), "sync_state", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_state_user_id"), table_name="sync_state")
    op.drop_table("sync_state")
    op.drop_index(op.f("ix_sync_conflicts_user_id"), table_name="sync_conflicts")
    op.drop_table("sync_conflicts")
    op.drop_index(op.f("ix_sync_agreements_user_id"), table_name="sync_agreements")
    op.drop_index(op.f("ix_sync_agreements_record_id"), table_name="sync_agreements")
    op.drop_table("sync_agreements")
    # ### end Alembic commands ###
