"""personal_info allows multiple rows per user

Revision ID: d83dad4c5f97
Revises: 8c831ca53e75
Create Date: 2026-08-09 21:57:20.841464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83dad4c5f97'
down_revision: Union[str, Sequence[str], None] = '8c831ca53e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('personal_info_user_id_key'), 'personal_info', type_='unique')
    op.create_index(op.f('ix_personal_info_user_id'), 'personal_info', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personal_info_user_id'), table_name='personal_info')
    op.create_unique_constraint(op.f('personal_info_user_id_key'), 'personal_info', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
